In [1]:
import numpy as np
import pandas as pd

In [3]:
df = pd.DataFrame({
    'Feature': np.arange(1,11),
    'Target': np.array([1,1,1,2,2,2,2,3,3,3])
})
df

   Feature  Target
0        1       1
1        2       1
2        3       1
3        4       2
4        5       2
5        6       2
6        7       2
7        8       3
8        9       3
9       10       3

In [12]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(
    df[['Feature']],
    df[['Target']],
    test_size= .30,
    random_state=43,
    stratify=df['Target']
)

In [13]:
pd.concat([x_train, y_train], axis=1)

   Feature  Target
8        9       3
1        2       1
3        4       2
4        5       2
7        8       3
2        3       1
5        6       2

In [14]:
pd.concat([x_test, y_test], axis=1)

   Feature  Target
0        1       1
6        7       2
9       10       3