- Pandas Series

In [77]:
import numpy as np
import pandas as pd

In [78]:
data = np.arange(5,10)
data

array([5, 6, 7, 8, 9])

In [79]:
pd_series = pd.Series(data = data)
pd_series

0    5
1    6
2    7
3    8
4    9
dtype: int64

In [80]:
pd_series[0]

np.int64(5)

In [81]:
index = ['a','b','c','d','e']

In [82]:
pd_series2 = pd.Series(data = data, index = index)
pd_series2

a    5
b    6
c    7
d    8
e    9
dtype: int64

In [83]:
pd_series2['a']

np.int64(5)

In [84]:
pd_series.index = index
pd_series

a    5
b    6
c    7
d    8
e    9
dtype: int64

In [85]:
data = {
    'a' : 2,
    'b' : 45,
    'c' : 456,
    'd' : 34,
    'e' : 23
}

pd_series3 = pd.Series(data = data)
pd_series3

a      2
b     45
c    456
d     34
e     23
dtype: int64

- Data Frames

In [86]:
data = np.random.rand(6,5)
data

array([[0.43214807, 0.70860552, 0.28000947, 0.95765361, 0.02690251],
       [0.67239483, 0.52871478, 0.56205931, 0.51086844, 0.41246736],
       [0.01947347, 0.63709126, 0.71937069, 0.88676985, 0.6489095 ],
       [0.48208816, 0.55910783, 0.52653961, 0.34226688, 0.45074293],
       [0.31773478, 0.73858926, 0.48366249, 0.69629377, 0.03339995],
       [0.90169306, 0.34252559, 0.95583169, 0.29930962, 0.23649617]])

In [87]:
df = pd.DataFrame(data = data)
df

          0         1         2         3         4
0  0.432148  0.708606  0.280009  0.957654  0.026903
1  0.672395  0.528715  0.562059  0.510868  0.412467
2  0.019473  0.637091  0.719371  0.886770  0.648910
3  0.482088  0.559108  0.526540  0.342267  0.450743
4  0.317735  0.738589  0.483662  0.696294  0.033400
5  0.901693  0.342526  0.955832  0.299310  0.236496

In [88]:
df[1]

0    0.708606
1    0.528715
2    0.637091
3    0.559108
4    0.738589
5    0.342526
Name: 1, dtype: float64

In [89]:
type(df)

pandas.DataFrame

In [90]:
df2 = pd.DataFrame(
    data = data, 
index = [1,2,3,4,5,6], 
columns = ['A','B','C','D','E']
)
df2

          A         B         C         D         E
1  0.432148  0.708606  0.280009  0.957654  0.026903
2  0.672395  0.528715  0.562059  0.510868  0.412467
3  0.019473  0.637091  0.719371  0.886770  0.648910
4  0.482088  0.559108  0.526540  0.342267  0.450743
5  0.317735  0.738589  0.483662  0.696294  0.033400
6  0.901693  0.342526  0.955832  0.299310  0.236496

In [91]:
df2[['A','B']]

          A         B
1  0.432148  0.708606
2  0.672395  0.528715
3  0.019473  0.637091
4  0.482088  0.559108
5  0.317735  0.738589
6  0.901693  0.342526

In [92]:
df2['F'] = np.random.rand(6)
df2

          A         B         C         D         E         F
1  0.432148  0.708606  0.280009  0.957654  0.026903  0.986333
2  0.672395  0.528715  0.562059  0.510868  0.412467  0.564887
3  0.019473  0.637091  0.719371  0.886770  0.648910  0.892943
4  0.482088  0.559108  0.526540  0.342267  0.450743  0.899738
5  0.317735  0.738589  0.483662  0.696294  0.033400  0.053150
6  0.901693  0.342526  0.955832  0.299310  0.236496  0.571930

In [93]:

# df2.drop('B', inplace=True, axis=1)

In [94]:
df2

          A         B         C         D         E         F
1  0.432148  0.708606  0.280009  0.957654  0.026903  0.986333
2  0.672395  0.528715  0.562059  0.510868  0.412467  0.564887
3  0.019473  0.637091  0.719371  0.886770  0.648910  0.892943
4  0.482088  0.559108  0.526540  0.342267  0.450743  0.899738
5  0.317735  0.738589  0.483662  0.696294  0.033400  0.053150
6  0.901693  0.342526  0.955832  0.299310  0.236496  0.571930

In [95]:
df2.shape

(6, 6)

In [96]:
df2.loc[1,'A']

np.float64(0.4321480679751355)

In [97]:
df2.loc[[1,2],['A','B']]

          A         B
1  0.432148  0.708606
2  0.672395  0.528715

In [98]:
df2.iloc[[0,1],[0,1]]

          A         B
1  0.432148  0.708606
2  0.672395  0.528715

- CONDITIONAL SELECTION

In [99]:
data = np.random.randn(6,5)
df = pd.DataFrame(
    data = data, 
    index = [1,2,3,4,5,6], 
    columns = ['A','B','C','D','E']
    )

df

          A         B         C         D         E
1 -0.938913 -0.799469  0.073458  1.389793 -1.164147
2 -0.828974 -0.540236  0.400308 -1.202441 -1.287384
3 -0.583385 -1.580718  1.395449  1.535866 -1.072878
4 -1.457779 -0.415083 -0.620926 -0.912344 -0.391032
5  0.821738 -0.978426 -0.968039 -0.399252  0.758548
6  1.777518 -0.105085 -0.061857 -0.963028  0.010406

In [100]:
bool_df = df > 0

df[bool_df]

          A   B         C         D         E
1       NaN NaN  0.073458  1.389793       NaN
2       NaN NaN  0.400308       NaN       NaN
3       NaN NaN  1.395449  1.535866       NaN
4       NaN NaN       NaN       NaN       NaN
5  0.821738 NaN       NaN       NaN  0.758548
6  1.777518 NaN       NaN       NaN  0.010406

method 2

In [101]:
df[df>0]

          A   B         C         D         E
1       NaN NaN  0.073458  1.389793       NaN
2       NaN NaN  0.400308       NaN       NaN
3       NaN NaN  1.395449  1.535866       NaN
4       NaN NaN       NaN       NaN       NaN
5  0.821738 NaN       NaN       NaN  0.758548
6  1.777518 NaN       NaN       NaN  0.010406

In [102]:
bool_series =df['A'] > 0

In [103]:
df[bool_series]

          A         B         C         D         E
5  0.821738 -0.978426 -0.968039 -0.399252  0.758548
6  1.777518 -0.105085 -0.061857 -0.963028  0.010406

METHOD 2

In [104]:
df[df['A'] > 0]

          A         B         C         D         E
5  0.821738 -0.978426 -0.968039 -0.399252  0.758548
6  1.777518 -0.105085 -0.061857 -0.963028  0.010406

OR = | OPERATOR

In [105]:
df

          A         B         C         D         E
1 -0.938913 -0.799469  0.073458  1.389793 -1.164147
2 -0.828974 -0.540236  0.400308 -1.202441 -1.287384
3 -0.583385 -1.580718  1.395449  1.535866 -1.072878
4 -1.457779 -0.415083 -0.620926 -0.912344 -0.391032
5  0.821738 -0.978426 -0.968039 -0.399252  0.758548
6  1.777518 -0.105085 -0.061857 -0.963028  0.010406

In [106]:
bool_series2 = (df['A'] > 0)  | (df['B'] < 0)

METHOD 1

In [107]:
res = df[bool_series2]
res[['C','D']]

          C         D
1  0.073458  1.389793
2  0.400308 -1.202441
3  1.395449  1.535866
4 -0.620926 -0.912344
5 -0.968039 -0.399252
6 -0.061857 -0.963028

METHOD 2

In [108]:
df[(df['A'] > 0) | (df['B'] < 0)][['C','D']]

          C         D
1  0.073458  1.389793
2  0.400308 -1.202441
3  1.395449  1.535866
4 -0.620926 -0.912344
5 -0.968039 -0.399252
6 -0.061857 -0.963028

In [109]:
groups = ['group1']*3 + ['group2']*3
inside_groups = ['row1','row2','row3']*2
columns = ['col1','col2','col3']
tup = list(zip(groups, inside_groups))

- MULTI INDEX

In [110]:
groups = ['group1']*3 + ['group2']*3
groups

['group1', 'group1', 'group1', 'group2', 'group2', 'group2']

In [111]:
inside_groups = ['row1','row2','row3']*2
inside_groups

['row1', 'row2', 'row3', 'row1', 'row2', 'row3']

In [112]:
columns = ['col1','col2','col3']

In [113]:
indtup = list(zip(groups, inside_groups))

In [114]:
index = pd.MultiIndex.from_tuples(tuples=indtup)
index

MultiIndex([('group1', 'row1'),
            ('group1', 'row2'),
            ('group1', 'row3'),
            ('group2', 'row1'),
            ('group2', 'row2'),
            ('group2', 'row3')],
           )

In [115]:
df4 = pd.DataFrame(
    data = np.random.randn(6,3), 
    index = index, 
    columns = columns
)

df4

                 col1      col2      col3
group1 row1  0.522191 -0.099937  0.859919
       row2 -2.863814 -0.531987  0.342661
       row3  0.606972  0.161428 -0.549666
group2 row1 -2.907604 -0.186555 -1.081362
       row2 -0.165817  2.935788 -0.204645
       row3 -0.208995  0.754701  0.114752

In [116]:
group1 = df4.loc['group1']
group1

          col1      col2      col3
row1  0.522191 -0.099937  0.859919
row2 -2.863814 -0.531987  0.342661
row3  0.606972  0.161428 -0.549666

In [117]:
group1.loc['row1']

col1    0.522191
col2   -0.099937
col3    0.859919
Name: row1, dtype: float64

In [118]:
df4.loc['group1'].loc['row1'].loc['col1']

np.float64(0.5221905054092523)

In [119]:
df4.index.names = ['groups', 'rows']

In [120]:
df4

                 col1      col2      col3
groups rows
group1 row1  0.522191 -0.099937  0.859919
       row2 -2.863814 -0.531987  0.342661
       row3  0.606972  0.161428 -0.549666
group2 row1 -2.907604 -0.186555 -1.081362
       row2 -0.165817  2.935788 -0.204645
       row3 -0.208995  0.754701  0.114752

In [121]:
df4.xs('row1', level='rows')

            col1      col2      col3
groups
group1  0.522191 -0.099937  0.859919
group2 -2.907604 -0.186555 -1.081362

# missing value handle

In [122]:
data = {
    'A' : [1,2, 3, 4, 5],
    'B' : [5, np.nan, np.nan, 8, 9],
    'C' : [10, 11, 12, np.nan, 14]
}
df = pd.DataFrame(data = data)
df

   A    B     C
0  1  5.0  10.0
1  2  NaN  11.0
2  3  NaN  12.0
3  4  8.0   NaN
4  5  9.0  14.0

In [123]:
df.dropna(axis=0, thresh=3)

   A    B     C
0  1  5.0  10.0
4  5  9.0  14.0

In [124]:
df

   A    B     C
0  1  5.0  10.0
1  2  NaN  11.0
2  3  NaN  12.0
3  4  8.0   NaN
4  5  9.0  14.0

In [125]:
df.fillna(value = 'missing')

   A        B        C
0  1      5.0     10.0
1  2  missing     11.0
2  3  missing     12.0
3  4      8.0  missing
4  5      9.0     14.0

In [126]:
df.fillna(value = df['A'].mean())

   A    B     C
0  1  5.0  10.0
1  2  3.0  11.0
2  3  3.0  12.0
3  4  8.0   3.0
4  5  9.0  14.0

In [127]:
df.fillna({'B' : df['B'].mean()})

   A         B     C
0  1  5.000000  10.0
1  2  7.333333  11.0
2  3  7.333333  12.0
3  4  8.000000   NaN
4  5  9.000000  14.0

# Pandas group

In [133]:
data2 = {
    'Store Name' : ['Pizza Hut', 'Dominos', 'Pizza Hut', 'Little Caesars', 'Marcos Pizza'],
    'Location' : ['New York', 'Los Angeles', 'Ponchobeki', 'Houston', 'Phoenix'],
    'Price' : np.random.randint(300,500, size=5)
}

df5 = pd.DataFrame(data2)
df5

       Store Name     Location  Price
0       Pizza Hut     New York    382
1         Dominos  Los Angeles    307
2       Pizza Hut   Ponchobeki    473
3  Little Caesars      Houston    395
4    Marcos Pizza      Phoenix    347

In [129]:
df5.groupby('Store Name').max()

                   Location  Price
Store Name
Dominos         Los Angeles    362
Little Caesars      Houston    341
Marcos Pizza        Phoenix    364
Pizza Hut          New York    348

In [134]:
store = df5.groupby('Store Name')
store

In [137]:
store.mean(numeric_only=True)

                Price
Store Name
Dominos         307.0
Little Caesars  395.0
Marcos Pizza    347.0
Pizza Hut       427.5

In [136]:
store.sum(numeric_only=True)

                Price
Store Name
Dominos           307
Little Caesars    395
Marcos Pizza      347
Pizza Hut         855

In [138]:
store.describe()

               Price
               count   mean        std    min     25%    50%     75%    max
Store Name
Dominos          1.0  307.0        NaN  307.0  307.00  307.0  307.00  307.0
Little Caesars   1.0  395.0        NaN  395.0  395.00  395.0  395.00  395.0
Marcos Pizza     1.0  347.0        NaN  347.0  347.00  347.0  347.00  347.0
Pizza Hut        2.0  427.5  64.346717  382.0  404.75  427.5  450.25  473.0